# Generated by Django 3.0.1 on 2020-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('file_csv', models.FileField(upload_to='csv_data/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
